# -*- coding: utf-8 -*-
"""Sampling_project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q0QLmG3K8Ewx3RwAw7i06SnGBtoB-h3m

Sampling Project, 3BSHDSA
*   Name: Aadarsha Gautam
*   USN no.:21BSR18059
"""

import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_rows', 100)

df=pd.read_csv("Dat.csv")

df.info()
df.head()

df1=df[df['Player']=='Messi']
df2=df[df['Player']=='Ronaldo']

df1.head()

df2.head()

df=df.iloc[::-1]
df

plt.figure(figsize=(15,15))
plt.subplot(421)
df.groupby('Player')['LaLigaGoals'].sum().plot.bar()
plt.title('LaLigaGoals')
plt.subplot(422)
df.groupby('Player')['LaLigaAsts'].sum().plot.bar()
plt.title('LaLigaAsts')
plt.subplot(423)
df.groupby('Player')['LaLigaAps'].sum().plot.bar()
plt.title('LaLigaAps')
plt.subplot(424)
df.groupby('Player')['LaLigaMins'].sum().plot.bar()
plt.title('LaLigaMins')
plt.subplot(425)
df.groupby('Player')['CLGoals'].sum().plot.bar()
plt.title('CLGoals')
plt.subplot(426)
df.groupby('Player')['CLAsts'].sum().plot.bar()
plt.title('CLAsts')
plt.subplot(427)
df.groupby('Player')['CLAps'].sum().plot.bar()
plt.title('CLAps')
plt.subplot(428)
df.groupby('Player')['CLMins'].sum().plot.bar()
plt.title('CLMins')
plt.subplots_adjust(hspace=1)
plt.subplots_adjust(wspace=1)

df['MpLLG']=df['LaLigaGoals']/df['LaLigaMins']
df['MpLAs']=df['LaLigaAsts']/df['LaLigaMins']
df['MpLAp']=df['LaLigaAps']/df['LaLigaGoals']
df['MpCLG']=df['CLGoals']/df['CLMins']
df['MpCLAs']=df['CLAsts']/df['CLMins']
df['MpCLAp']=df['CLAps']/df['CLMins']

df1['MMpLLG']=df1['LaLigaGoals']/df1['LaLigaMins']
df1['MMpLAs']=df1['LaLigaAsts']/df1['LaLigaMins']
df1['MMpLAp']=df1['LaLigaAps']/df1['LaLigaGoals']
df1['MMpCLG']=df1['CLGoals']/df1['CLMins']
df1['MMpCLAs']=df1['CLAsts']/df1['CLMins']
df1['MMpCLAp']=df1['CLAps']/df1['CLMins']

df2['RMpLLG']=df2['LaLigaGoals']/df2['LaLigaMins']
df2['RMpLAs']=df2['LaLigaAsts']/df2['LaLigaMins']
df2['RMpLAp']=df2['LaLigaAps']/df2['LaLigaGoals']
df2['RMpCLG']=df2['CLGoals']/df2['CLMins']
df2['RMpCLAs']=df2['CLAsts']/df2['CLMins']
df2['RMpCLAp']=df2['CLAps']/df2['CLMins']

plt.figure(figsize=(20,20))
plt.subplot(441)
sns.barplot(data=df,x='Season',y='LaLigaGoals',hue='Player',palette={'Messi':'red','Ronaldo':'green'})
plt.title('LaLigaGoals', size=10)
plt.xticks(rotation=45)

plt.subplot(442)
sns.barplot(data=df,x='Season',y='LaLigaAsts',hue='Player',palette={'Messi':'red','Ronaldo':'green'})
plt.title('LaLigaAsts', size=10)
plt.xticks(rotation=45)

plt.subplot(443)
sns.barplot(data=df,x='Season',y='LaLigaAps',hue='Player',palette={'Messi':'red','Ronaldo':'green'})
plt.title('LaLigaAps', size=10)
plt.xticks(rotation=45)

plt.subplot(444)
sns.barplot(data=df,x='Season',y='LaLigaMins',hue='Player',palette={'Messi':'red','Ronaldo':'green'})
plt.title('LaLigaMins', size=10)
plt.xticks(rotation=45)

plt.subplot(445)
sns.barplot(data=df,x='Season',y='CLGoals',hue='Player',palette={'Messi':'red','Ronaldo':'green'})
plt.title('CLGoals', size=10)
plt.xticks(rotation=45)

plt.subplot(446)
sns.barplot(data=df,x='Season',y='CLAsts',hue='Player',palette={'Messi':'red','Ronaldo':'green'})
plt.title('CLAsts', size=10)
plt.xticks(rotation=45)

plt.subplot(447)
sns.barplot(data=df,x='Season',y='CLAps',hue='Player',palette={'Messi':'red','Ronaldo':'green'})
plt.title('CL_Ap', size=10)
plt.xticks(rotation=45)

plt.subplot(448)
sns.barplot(data=df,x='Season',y='CLMins',hue='Player',palette={'Messi':'red','Ronaldo':'green'})
plt.title('CLMins', size=10)
plt.xticks(rotation=45)

plt.subplots_adjust(wspace=0.4, hspace=0.6)
plt.show()

plt.figure(figsize = (15,8))
sns.heatmap(df1.corr(),annot=True, fmt="1.1f")
plt.figure(figsize = (15,8))
sns.heatmap(df2.corr(),annot=True, fmt="1.1f")

plt.figure(figsize = (15,8))
sns.pairplot(df,hue='Player')

plt.figure(figsize=(12, 12))
plt.legend(fontsize=10)
plt.tick_params(labelsize=10)
ax=sns.scatterplot(y=df['LaLigaAsts'],x=df['LaLigaGoals'],hue=df['Player'],data=df,sizes=(200,50))
plt.xticks(rotation=90)
ax.legend(loc='upper left',bbox_to_anchor=(1,1))

plt.figure(figsize=(12, 12))
plt.legend(fontsize=10)
plt.tick_params(labelsize=10)
ax=sns.scatterplot(y=df['CLAsts'],x=df['CLGoals'],hue=df['Player'],data=df,sizes=(200,50))
plt.xticks(rotation=90)
ax.legend(loc='upper left',bbox_to_anchor=(1,1))

from scipy import stats as st
st.ttest_ind(a=(df1['MMpLLG']), b=(df2['RMpLLG']), equal_var=True)

st.ttest_ind(a=(df1['MMpLAs']), b=(df2['RMpLAs']), equal_var=True)

st.ttest_ind(a=(df1['MMpLAp']), b=(df2['RMpLAp']), equal_var=True)

st.ttest_ind(a=(df1['MMpCLG']), b=(df2['RMpCLG']), equal_var=True)

st.ttest_ind(a=(df1['MMpCLAs']), b=(df2['RMpCLAs']), equal_var=True)

st.ttest_ind(a=(df1['MMpCLAp']), b=(df2['RMpCLAp']), equal_var=True)